steps:
  - id: install-test-dependencies
    name: node:20-bookworm
    dir: test-runner
    entrypoint: npm
    args:
      - install
      - --no-audit
      - --no-fund

  - id: test-generated-implementations
    name: node:20-bookworm
    dir: test-runner
    entrypoint: npm
    args:
      - run
      - test:generated
    allowExitCodes: [1]

  - id: upload-test-results
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage cp \
          --recursive \
          requirements/ai/generated/test-results \
          gs://aidf-team-suda.appspot.com/ai-development/$BUILD_ID/

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s